### ISSUE TITLE
Error in rule multiqc

### ISSUE THREAD

**Issue by faye-romero** [hsigeman/findZX#13]
Hi @hsigeman , I'm having some troubles with multiqc when trying to execute the test run for findZX-synteny. Please see below:

```
#Command: snakemake -s workflow/findZX-synteny --configfile .test/config.yml --cores 1 -R all -k --use-conda

Activating conda environment: /gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/646ebc8c8060df2eb7d0180418264cff
Traceback (most recent call last):
  File "/gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/75643c95c204e7a7b27a378eab517100/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/75643c95c204e7a7b27a378eab517100/lib/python3.12/site-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/75643c95c204e7a7b27a378eab517100/lib/python3.12/site-packages/multiqc/multiqc.py", line 42, in <module>
    from .plots import table
  File "/gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/75643c95c204e7a7b27a378eab517100/lib/python3.12/site-packages/multiqc/plots/table.py", line 9, in <module>
    from multiqc.utils import config, report, util_functions, mqc_colour
  File "/gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/75643c95c204e7a7b27a378eab517100/lib/python3.12/site-packages/multiqc/utils/report.py", line 13, in <module>
    import lzstring
  File "/gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/75643c95c204e7a7b27a378eab517100/lib/python3.12/site-packages/lzstring/__init__.py", line 11, in <module>
    from future import standard_library
  File "/gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/75643c95c204e7a7b27a378eab517100/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
[Mon Oct 30 10:21:00 2023]
Error in rule multiqc:
    jobid: 1
    output: results/howler_monkey_test_dataset/qc/fastqc/multiqc.untrimmed.html
    log: results/howler_monkey_test_dataset/logs/fastqc/multiqc.log (check log file(s) for error message)
    conda-env: /gpfs/fs2/scratch/fromero3/findZX/.snakemake/conda/75643c95c204e7a7b27a378eab517100
    shell:
        multiqc results/howler_monkey_test_dataset/qc/fastqc/subset_SRR9655168__homogametic.untrimmed_fastqc.zip results/howler_monkey_test_dataset/qc/fastqc/subset_SRR9655169__homogametic.untrimmed_fastqc.zip results/howler_monkey_test_dataset/qc/fastqc/subset_SRR9655170__heterogametic.untrimmed_fastqc.zip results/howler_monkey_test_dataset/qc/fastqc/subset_SRR9655171__heterogametic.untrimmed_fastqc.zip -n results/howler_monkey_test_dataset/qc/fastqc/multiqc.untrimmed.html -f
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

I've looked at the other issues with multiqc (e.g. https://github.com/hsigeman/findZX/issues/2), but this one seems to be independent of updated changes to the pipeline. Any help would be much appreciated.

**Comment by faye-romero** [comment]
The `imp` module was deprecated in python 3.12. This error was solved by changing multiqc.yaml to the following:

```shell
channels:
  - conda-forge
  - bioconda
dependencies:
  - python<3.12
  - multiqc=1.11
```
