### ISSUE TITLE
MultiQC 1.10.1 Modules break 

### ISSUE THREAD

**Issue by zhuangfjnu** [hsigeman/findZX#5]
[WARNING]         multiqc : MultiQC Version v1.11 now available!
[INFO   ]         multiqc : This is MultiQC v1.10.1 (3206687)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /share/workplace/HIC/Software/findZX/results/howler_monkey_test_dataset/qc/fastqc
Searching   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 8/8  
[ERROR  ]         multiqc : Oops! The 'custom_content' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module custom_content raised an exception: Traceback (most recent call last):
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/multiqc.py", line 594, in run
    output = mod()
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/modules/custom_content/custom_content.py", line 87, in custom_module_classes
    bm = BaseMultiqcModule()
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/modules/base_module.py", line 45, in __init__
    config.update({anchor: mod_cust_config.get("custom_config", {})})
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/utils/config.py", line 250, in update
    return update_dict(globals(), u)
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/utils/config.py", line 256, in update_dict
    if isinstance(val, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
============================================================
[ERROR  ]         multiqc : Oops! The 'ngsderive' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module ngsderive raised an exception: Traceback (most recent call last):
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/multiqc.py", line 594, in run
    output = mod()
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/modules/ngsderive/ngsderive.py", line 29, in __init__
    super(MultiqcModule, self).__init__(
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/modules/base_module.py", line 45, in __init__
    config.update({anchor: mod_cust_config.get("custom_config", {})})
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/utils/config.py", line 250, in update
    return update_dict(globals(), u)
  File "/share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7/lib/python3.10/site-packages/multiqc/utils/config.py", line 256, in update_dict
    if isinstance(val, collections.Mapping):

**Comment by hsigeman** [comment]
Hi, and thanks for reporting this issue. The latest version of findZX now uses the latest version of MultiQC (v.1.11), in which these problems are solved (see closed issue #2). Let me know if the problem persists after fetching the latest changes and I will look into it again!

Hanna

**Comment by zhuangfjnu** [comment]
> Let me know if the problem persists after fetching the latest changes and I will look into it again!

The  latest changes add a conda env for the mutiqc, But the workflow only activate the conda env for fastq

Job 4: Running FastQC on the untrimmed fastq file. Sample: subset_SRR9655170

Activating conda environment: /share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7
Activating conda environment: /share/workplace/HIC/Software/findZX/.snakemake/conda/e9e69d51a577afa8f54d5efc8cdd96c7
Traceback (most recent call last):
  File "/share/workplace/HIC/Software/findZX/.snakemake/scripts/tmpz3f807qz.wrapper.py", line 23, in <module>
    shell(
  File "/share/workplace/liu_test/soft/miniconda3/envs/findZX3/lib/python3.9/site-packages/snakemake/shell.py", line 231, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  multiqc  --force -o results/howler_monkey_test_dataset/qc/fastqc -n subset_SRR9655170__heterogametic.untrimmed.html .test  > results/howler_monkey_test_dataset/logs/fastqc/subset_SRR9655170__heterogametic.untrimmed.log 2>&1' returned non-zero exit status 1.

**Comment by hsigeman** [comment]
Hi Zhen, 

Sorry the program isn't working out well for you. It's strange that your installation is behaving so differently to mine. 

In order to help you with the troubleshooting, I would like to make sure that your conda environment is clean and that no potentially conflicting files are present in the findZX directory. Please make a fresh installation of both the conda environment and findZX by following these steps: 

```
# Remove conda environment
conda remove --name findZX --all

# Create new conda environment (I added "-c R" and "R=3.6.0" which I think might help with the incompatibility problems with your local R version)
conda create -n findZX -c conda-forge -c bioconda -c R python=3.9.4 snakemake-wrapper-utils=0.2.0 snakemake=6.4.0 mamba=0.15.3 R=3.6.0

# Remove findZX directory
rm -r findZX 

# Fetch the latest version of findZX again
git clone https://github.com/hsigeman/findZX.git 

# Go to directory
cd findZX 

# Run the test dataset
snakemake -s workflow/findZX-synteny --configfile .test/config.yml -k --cores 3 -R all --use-conda
```

This worked without errors for me on both a macOS and a CentOS Linux operating system. What is happening when you run this, and what OS are you running? 

Hanna
